# Routers that know all routes
route_source:
  rt1:
    type: Cisco
    name: rt1-001
  rt2:
    type: Cisco
    name: rt2-002
# Firewall data
firewalls:
  fw1:
    type: Palo
    name: fw1-0001
    vsys: VR-1
  fw2:
    type: Palo
    name: fw2-0002
    vsys: VR-2
routes_to_outside:
  '192.168.245.138': fw1
  '192.168.245.139': fw2
#naming convention - prefixes to objects created by the app should be uniq and complex to make sure that the objects
#are not created by other app or human by accident. 
convention:
  addr-group-pref: ag-
  sec-rule-pref: rule-