# Core routers
#cisco_nxos_ssh - nazwa modułu, CiscoNxosSSH - nazwa obiektu w module
core:
- core-r1
- core-r2
# Firewall data
firewalls:
  fw1:
    type: Palo
    name: fw1-0001
    zone: VR-1
  fw2:
    type: Palo
    name: fw2-0002
    zone: VR-2
routes:
  '192.168.245.138': fw1
  '192.168.245.139': fw2